# Generated by Django 3.2.5 on 2021-10-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0003_auto_20210930_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='TrangChu.foodcategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='TrangChu.servicecategory'),
        ),
        migrations.AlterField(
            model_name='weddingroom',
            name='wedding_room_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weddingrooms', to='TrangChu.weddingroomtype'),
        ),
    ]
