# Generated by Django 3.2.5 on 2021-08-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0003_auto_20210827_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingbill',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='CustomerBill', to='TrangChu.customer'),
        ),
    ]
