# Generated by Django 3.2.5 on 2021-08-30 02:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0004_alter_weddingbill_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddingroom',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
