# Generated by Django 3.2.5 on 2021-10-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0007_auto_20211006_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
