# Generated by Django 3.2.5 on 2021-10-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0007_alter_weddingroomdetails_wedding_room'),
        ('TrangChu', '0007_auto_20211006_2133'),
    ]

    operations = [
    ]
