# Generated by Django 3.2.5 on 2021-10-25 02:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0009_auto_20211021_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingbill',
            name='customer',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddingbill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customerbill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weddingroom',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
