# Generated by Django 3.2.5 on 2021-10-22 04:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0009_auto_20211021_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='weddingroom',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
