# Generated by Django 3.2.5 on 2021-10-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0008_contact_address'),
        ('TrangChu', '0010_comment'),
    ]

    operations = [
    ]
