# Generated by Django 3.2.5 on 2021-12-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrangChu', '0010_auto_20211025_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingbill',
            name='employee',
        ),
        migrations.AddField(
            model_name='weddingbill',
            name='menus',
            field=models.ManyToManyField(blank=True, null=True, related_name='bill_menus', through='TrangChu.MenuInBill', to='TrangChu.Menu'),
        ),
        migrations.AddField(
            model_name='weddingbill',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='bill_services', through='TrangChu.ServiceInBill', to='TrangChu.Service'),
        ),
        migrations.AlterField(
            model_name='serviceinbill',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicebills', to='TrangChu.service'),
        ),
    ]
